spring.profiles.active: product
logging.config: classpath:log4j2.xml
server:
  port: 8080
  servlet.context-path: /


# 需要探活的服务列表（格式一）
detected-list:
  remoteServices:
    - name: "exp"
      protocol: "http"
      address: "https://exp-blog.com"
    - name: "qq"
      protocol: "socket"
      address: "127.0.0.1:65535"


# 需要探活的服务列表（格式二）
detected-list.remoteServices[2].name: "baidu"
detected-list.remoteServices[2].protocol: "http"
detected-list.remoteServices[2].address: "https://www.baidu.com"
detected-list.remoteServices[3].name: "springboot"
detected-list.remoteServices[3].protocol: "socket"
detected-list.remoteServices[3].address: "127.0.0.1:8080"

